package com.yuehai.util.eventbus

//房间麦位操作相关
val EVENT_MESSAGE_ROOM_MIC_OPERATE = "EVENT_MESSAGE_ROOM_MIC_OPERATE"
val EVENT_MESSAGE_ROOM_THEME_OPERATE = "EVENT_MESSAGE_ROOM_THEME_OPERATE"
val EVENT_MESSAGE_ROOM_GAME_OPERATE = "EVENT_MESSAGE_ROOM_GAME_OPERATE"

//房间麦克风音量
val EVENT_ROOM_MIC_VOLUME_OPERATE = "EVENT_ROOM_MIC_VOLUME_OPERATE"

//房间点击播放音乐
val EVENT_ROOM_MUSIC_PLAY_OPERATE = "EVENT_ROOM_MUSIC_PLAY_OPERATE"

//踢出房间
val EVENT_MESSAGE_ROOM_KICK_OUT = "EVENT_MESSAGE_ROOM_KICK_OUT"
val EVENT_MESSAGE_ROOM_BANN_ROOM = "EVENT_MESSAGE_ROOM_BANN_ROOM"

//邀请上麦
val EVENT_MESSAGE_ROOM_INVITE_ON_MIC = "EVENT_MESSAGE_ROOM_INVITE_ON_MIC"

//有人进房
val EVENT_MESSAGE_ROOM_MEMBER_IN = "EVENT_MESSAGE_ROOM_MEMBER_IN"
val EVENT_MESSAGE_ROOM_MEMBER_SELF_IN = "EVENT_MESSAGE_ROOM_MEMBER_SELF_IN"

//别人人进房
val EVENT_MESSAGE_ROOM_OTHER_MEMBER_IN = "EVENT_MESSAGE_ROOM_OTHER_MEMBER_IN"

//有人出房
val EVENT_MESSAGE_ROOM_MEMBER_OUT = "EVENT_MESSAGE_ROOM_MEMBER_OUT"

//有人被踢出房
val EVENT_MESSAGE_ROOM_MEMBER_KICK_OUT = "EVENT_MESSAGE_ROOM_MEMBER_KICK_OUT"

//魅力值开关
val EVENT_MESSAGE_ROOM_CHARM_SWITCH = "EVENT_MESSAGE_ROOM_CHARM_SWITCH"

//礼物信息
val EVENT_MESSAGE_ROOM_GIFT_CHARM = "EVENT_MESSAGE_ROOM_GIFT_CHARM"

//禁止用戶評論
val EVENT_MESSAGE_ROOM_FORBID_COMMENT = "EVENT_MESSAGE_ROOM_FORBID_COMMENT"

//允許用戶評論
val EVENT_MESSAGE_ROOM_COMMENT = "EVENT_MESSAGE_ROOM_COMMENT"

//设置用户未管理员
val EVENT_MESSAGE_SET_ADMIN = "EVENT_MESSAGE_SET_ADMIN"

//设置用户取消管理员
val EVENT_MESSAGE_CANCEL_ADMIN = "EVENT_MESSAGE_CANCEL_ADMIN"

//更改房间信息
val EVENT_MESSAGE_ROOM_NORMAL_INFO = "EVENT_MESSAGE_ROOM_NORMAL_INFO"

//更改房间主题信息
val EVENT_MESSAGE_ROOM_THEME_INFO = "EVENT_MESSAGE_ROOM_THEME_INFO"


//更改房间游戏主题
val EVENT_MESSAGE_GAME_THEM = "EVENT_MESSAGE_GAME_THEM"

//创建房间主题
val EVENT_MESSAGE_CREATE_THEM = "EVENT_MESSAGE_CREATE_THEM"

//麦位表情包
val EVENT_MESSAGE_ROOM_MIC_SETA_EMOTION = "EVENT_MESSAGE_ROOM_MIC_SETA_EMOTION"

//退出房间
val EVENT_MESSAGE_LOGOUT_ROOM = "EVENT_MESSAGE_LOGOUT_ROOM"

//关注
val EVENT_MESSAGE_PERSON_FOLLOW = "EVENT_MESSAGE_PERSON_FOLLOW"


//关注im

const val EVENT_MESSAGE_PERSON_IM_FOLLOW = "event_message_person_im_follow"


//im未读的消息数量
val EVENT_MESSAGE_PERSON_IM_UNREAD_COUNT = "EVENT_MESSAGE_PERSON_IM_UNREAD_COUNT"

//im未读的系统消息
val EVENT_MESSAGE_SYSTEM_IM_UNREAD_COUNT = "EVENT_MESSAGE_SYSTEM_IM_UNREAD_COUNT"
val EVENT_MESSAGE_SYSTEM_IM_READ_COUNT = "EVENT_MESSAGE_SYSTEM_IM_READ_COUNT"

//im未读的系统活动消息
val EVENT_MESSAGE_ACTIVITY_IM_UNREAD_COUNT = "EVENT_MESSAGE_ACTIVITY_IM_UNREAD_COUNT"
val EVENT_MESSAGE_ACTIVITY_IM_READ_COUNT = "EVENT_MESSAGE_ACTIVITY_IM_READ_COUNT"


//全服幸运礼物
val EVENT_ROOM_LUCKY_GIFT_ALL = "EVENT_ROOM_LUCKY_GIFT_ALL"

//全服游戏礼物
val EVENT_ROOM_GAME_REWARD = "EVENT_ROOM_GAME_REWARD"

//全服游戏礼物
val EVENT_ROOM_CHAT_GAME_REWARD = "EVENT_ROOM_CHAT_GAME_REWARD"

//全服礼物
val EVENT_ROOM_GIFT_ALL = "EVENT_ROOM_GIFT_ALL"

//幸运礼物
val EVENT_ROOM_GIFT_LUCK = "EVENT_ROOM_GIFT_LUCK"


//幸运礼物连击
val EVENT_ROOM_GIFT_COMBO = "EVENT_ROOM_GIFT_COMBO"

//选择国家列表电话号码前缀
val EVENT_MESSAGE_COUNTRY_PHONE_CODE = "EVENT_MESSAGE_COUNTRY_PHONE_CODE"


//注册成功
val EVENT_MESSAGE_LOGIN_REGISTER = "EVENT_MESSAGE_LOGIN_REGISTER"

//房间修改麦位数量类型
val EVENT_MESSAGE_MIC_MODE_CHANGE = "EVENT_MESSAGE_MIC_MODE_CHANGE"

//房间公屏名字顔色
val EVENT_MESSAGE_ROOM_HIGH_LIGHT_NAME_SWITCH = "EVENT_MESSAGE_ROOM_HIGH_LIGHT_NAME_SWITCH"

//房间隐身状态
val EVENT_MESSAGE_ROOM_TURN_OFF_INCOGINITO_SWITCH = "EVENT_MESSAGE_ROOM_TURN_OFF_INCOGINITO_SWITCH"

//房间背景
val EVENT_MESSAGE_ROOM_BACKGROUND = "EVENT_MESSAGE_ROOM_BACKGROUND"

//音乐预览

val EVENT_MUSIC_PREVIEW = "EVENT_MUSIC_PREVIEW"

val EVENT_IM_AGENCY_REJECT_INVITE = "EVENT_IM_AGENCY_REJECT_INVITE"

val EVENT_IM_AGENCY_AGREE_INVITE = "EVENT_IM_AGENCY_AGREE_INVITE"

val EVENT_IM_AGENCY_REJECT_APPLY = "EVENT_IM_AGENCY_REJECT_APPLY"

val EVENT_IM_AGENCY_AGREE_APPLY = "EVENT_IM_AGENCY_AGREE_APPLY"
val EVENT_IM_AGENCY_UPDATE = "EVENT_IM_AGENCY_UPDATE"

//从外部结束掉房间activity
val EVENT_ROOM_ACTIVITY_TASK_FINISH="EVENT_ROOM_ACTIVITY_TASK_FINISH"

val EVENT_ROOM_LUCKY_BAG_APPLICAITON_ALL = "EVENT_ROOM_LUCKY_BAG_APPLICAITON_ALL"
val EVENT_ROOM_LUCKY_BAG_GIFT_ALL = "EVENT_ROOM_LUCKY_BAG_GIFT_ALL"
val EVENT_ROOM_LUCKY_BAG_EXPIRED = "EVENT_ROOM_LUCKY_BAG_EXPIRED"
//房间火箭特效
val EVENT_ROOM_ROCKET_EFFECT = "EVENT_ROOM_ROCKET_EFFECT"
//房间火箭特
val EVENT_ROOM_ROCKET_BANNER = "EVENT_ROOM_ROCKET_BANNER"







