package com.yuehai.ui.widget

const val IM_UNREAD_COUNT_TAG="IM_UNREAD_COUNT_TAG"
const val SYSTEM_UNREAD_COUNT_TAG="SYSTEM_UNREAD_COUNT_TAG"
const val ACTIVITY_UNREAD_COUNT_TAG="ACTIVITY_UNREAD_COUNT_TAG"